name              'docker-engine'
maintainer        'Sous Chefs'
maintainer_email  'help@sous-chefs.org'
license           'Apache-2.0'
description       'Installs/Configures docker-engine'
source_url        'https://github.com/sous-chefs/docker-engine'
issues_url        'https://github.com/sous-chefs/docker-engine/issues'
chef_version      '>= 12.14'
version           '0.2.15'

supports 'ubuntu'
supports 'centos'
